/* ================================
Week 6 Assignment: Slide Model
================================ */
var obj1 = {title: "Philadelphia Neighborhoods!"};
var obj2 = {title: "Overbrook", subTitle: "Northwest of West Philadelphia", text: "Overbrook developed in various stages between 1900 and 1960. The dominant housing type is the row house, present in a wide variety of styles. Built in the early 20th century when trolley lines were allowing middle-class Philadelphians to move out from more crowded row house communities, Overbrook was a community of choice when it was built. Real estate advertisements in the Philadelphia Inquirer in the 1920s referred to the area as “exclusive.” Facades of all kinds grace the fronts of otherwise uniform brick and stone rowhouses. Typical rowhomes in Overbrook are between 1000 and 1,700 square feet (160 m2) in size. Companies such as the McClatchy Company, the John McGinty Company, and smaller developers such as the Moss and Taylor Company constructed most of Overbrook’s rowhouses.", sqlStatement: "listname = 'Overbrook'"};
var obj3 = {title: "Pennypack Park", subTitle: "Located in Northeast Philadelphia", text: "The Greenbelt Knoll Historic District and Holme Avenue Bridge, in Pennypack, are listed on the National Register of Historic Places.", sqlStatement: "listname = 'Pennypack Park'"};
var obj4 = {title: "Nicetown", subTitle: "A neighborhood in North Philadelphia", text: "Like most of North Philadelphia, the Nicetown area experienced periods of explosive industrial growth during the 1850's-1950's. The growth spurts waxed and waned with wars and recessions respectively, as did its ethnic diversity: Irish-Catholics from the famine in Ireland, the Polish-Jewish refugees from eastern Europe after World War II, the influx in the 1960s of African Americans escaping poverty and legal discrimination of the south, and surge of Puerto Rican relocation. All of these influxes were people of the blue collar and working class, which the neighborhood has always been, no matter which culture was largest at any particular time.", sqlStatement: "listname = 'Nicetown'"};
var obj5 = {title: "Oxford Circle", subTitle: "A neighborhood in the lower Northeast", text: "Most of the brick and stone row houses which characterize this neighborhood today were built by the Hyman Korman Company starting in the early 1940s and continuing into the 1950s. During that time and in the 1960s and 1970s Oxford Circle was a relatively prosperous white middle-class neighborhood and the majority of its residents were first and second generation Eastern European immigrants. White flight[5][6] and rising crime rates have dramatically changed the neighborhood since the late 1990s to early 2000s. Today's Oxford Circle contains a diverse population, including Caucasian, Jewish, Korean, Hispanic (mostly Puerto Ricans, Dominicans, and Brazilians), West Indian (mostly Haitians), and African American. Oxford Circle is about 37% Black, 32% White, 22% Hispanic, and 9% Asian.", sqlStatement: "listname = 'Oxford Circle'"};
var obj6 = {title: "Wister", subTitle: "A neighborhood in the Northwest", text: "Wister is bounded by Stenton Avenue to the north, Germantown Avenue to the south, Belfield Avenue to the east, and East Chelten Avenue to the west.[1][2] Wister is a section within Germantown. The Clarkson-Watson House, Fisher's Lane, Grumblethorpe, Grumblethorpe Tenant House, and Ivy Lodge are listed on the National Register of Historic Places.", sqlStatement: "listname = 'Wister'"};

var array = [obj1, obj2, obj3, obj4, obj5, obj6];
console.log(array);
